version: '3'
services:
  angular-starter:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: angular-starter
    networks:
      - angular-starter
    ports:
      - '3000:3000'
    volumes:
      - .:/home/app
      - /home/app/node_modules
networks:
  angular-starter:
    driver: bridge
